# Generated by Django 3.0.2 on 2020-02-15 06:34

import apps.schedules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('weight', models.IntegerField(default=9, verbose_name='权重')),
            ],
            options={
                'ordering': ['start_time', 'end_time', 'weight'],
                'get_latest_by': 'start_time',
            },
            bases=(models.Model, apps.schedules.models.CopyMixin),
        ),
        migrations.CreateModel(
            name='ScheduleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('permission', models.CharField(choices=[('0', 'public'), ('1', 'protected'), ('2', 'private')], default='2', max_length=10)),
            ],
            bases=(models.Model, apps.schedules.models.CopyMixin),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否完成')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.schedules.models.CopyMixin),
        ),
    ]
